//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinodnevnickAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Award_User
    {
        public int ID { get; set; }
        public Nullable<int> ID_Award { get; set; }
        public Nullable<int> ID_User { get; set; }
        public Nullable<bool> IsDone { get; set; }
    
        public virtual Award Award { get; set; }
        public virtual User User { get; set; }
    }
}
