//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinodnevnickAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int ID { get; set; }
        public Nullable<int> ID__Test { get; set; }
        public string Question1 { get; set; }
        public byte[] Photo { get; set; }
        public string Answer_One { get; set; }
        public string Answer_Two { get; set; }
        public string Answer_Three { get; set; }
        public string True_Answer { get; set; }
        public Nullable<bool> IsDone { get; set; }
    
        public virtual Test Test { get; set; }
    }
}
